# Generated by Django 3.0.4 on 2020-03-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='is_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
