# Generated by Django 3.0.4 on 2020-04-21 04:06

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='security',
            field=models.ImageField(default='default_secure.jpg', upload_to=accounts.models.content_file_name),
        ),
    ]
