# Generated by Django 2.0.3 on 2020-06-14 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_facespermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
