# Generated by Django 2.0.3 on 2020-06-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_friends_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='facespermission',
            name='allowed',
            field=models.BooleanField(default=False),
        ),
    ]
